# -*- coding: utf-8 -*-
"""news_positive

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eImFTnANb89q2l72p1yXZSqrPL6wUM7l
"""

# pip install feedparser
import feedparser
# pip install transformers
import requests

API_URL = "https://api-inference.huggingface.co/models/avichr/heBERT_sentiment_analysis"
headers = {"Authorization": "Bearer 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"}

def query(payload):
	response = requests.post(API_URL, headers=headers, json=payload)
	return response.json()

# URL of the RSS or Atom feed
feed_url = "https://www.thehindu.com/news/national/feeder/default.rss"

# Parse the feed
feed = feedparser.parse(feed_url)

entries = [entry['title'] + " " + entry.get('summary', '') for entry in feed.entries]

for entry in entries:
    output = query({"inputs": entry})

    # Access the first list in the output and iterate over its items
    for sentiment in output[0]:
        if sentiment['label'] == 'positive':
            print(f"Text: {entry}")
            print(f"Sentiment: {sentiment}")
            print("-" * 80)
            break  # Stop further checks if positive sentiment is found